const assert = require("node:assert/strict");

module.exports = async function checkEarthPosition(page) {
  const actual = await page.evaluate(() => {
    const { app } = window.test;
    const earth = app.planets.find(planet => planet.options.name === "Earth");
    if (!earth || !app.scene.children.includes(earth.body)) throw new Error("Earth is missing from the scene");
    const original = { jed: app.jed, speed: app.jedDelta };
    try {
      app.jedDelta = 0;
      return {
        ephemeris: earth.ephemeris,
        phases: app.planets.map(({ options, ephemeris }) => ({
          name: options.name, M: ephemeris.M, L: ephemeris.L, wbar: ephemeris.wbar,
        })),
        positions: [2451545, 2451636.314, 2451453.686, 2378861.5, 2488070.5].map(jed => {
          app.jed = jed;
          app.render();
          return earth.body.position.toArray();
        }),
      };
    } finally {
      app.jed = original.jed;
      app.render();
      app.jedDelta = original.speed;
    }
  });
  // NASA NSSDCA Earth Mean Orbital Elements (J2000) and sidereal period:
  // https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html
  // Keep this source cohort together; JPL's newer EM Bary fit differs.
  const source = {
    epoch: 2451545, a: 1.00000011, e: 0.01671022, i: 0.00005,
    W: -11.26064, w: 114.20783, wbar: 102.94719, L: 100.46435, P: 365.256,
  };
  for (const [key, value] of Object.entries(source)) {
    assert.equal(actual.ephemeris[key], value, `Earth uses the coherent J2000 source: ${key}`);
  }
  // Independently generated by Kepler bisection and successive plane rotations
  // using the source's L - wbar, never the application's stored M or solver.
  // J2000, quarter-period forward/reverse, then distant playback dates.
  const expected = [
    [-17.716175624839284, 96.72148794098914, 7.976156849822817e-5],
    [-97.63172650399369, -21.42782149947558, -3.497648723831389e-5],
    [98.98689279403717, 14.887987306053766, 2.961020242834101e-5],
    [-21.90286569520022, 95.85851448615269, 7.830953691862238e-5],
    [-17.544116286101282, 96.75297887991078, 7.981784066845575e-5],
  ];
  let maxPositionError = 0;
  actual.positions.forEach((position, i) => {
    const error = Math.hypot(...position.map((value, axis) => value - expected[i][axis]));
    assert(error < 1e-6, `Earth render at date case ${i}: ${error} world units from expected position`);
    maxPositionError = Math.max(maxPositionError, error);
  });
  assert.equal(actual.phases.length, 6, "Check every bundled planet's phase");
  for (const { name, M, L, wbar } of actual.phases) {
    const difference = (M - (L - wbar)) * Math.PI / 180;
    assert(Math.abs(Math.atan2(Math.sin(difference), Math.cos(difference))) < 1e-10,
      `${name}: mean anomaly agrees with its own L - wbar`);
  }
  return { datesChecked: actual.positions.length, planetsChecked: actual.phases.length, maxPositionError };
};
